user/models/user.py
from models import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(100), unique=False, nullable=False)
    last_name = db.Column(db.String(100), unique=False, nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    phone = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(200), unique=False, nullable=False)
    role = db.Column(db.String(200), unique=False, nullable=False)

    def __repr__(self):
        return f'<User {self.email}>'

user/controllers/user_controller.py
import hashlib
from flask import session
from models import db
from user.models.user import User
from config import Config

salt = Config.PASSWORD_HASH_SALT

def get_all_users():
    return User.query.all()

def create_user(first_name, last_name, email, phone, password):
    password = hash_password(password, salt)
    new_user = User(first_name=first_name, last_name=last_name, email=email, phone=phone, password=password)
    db.session.add(new_user)
    db.session.commit()

def hash_password(password, salt):
    password_hash = hashlib.sha256((password + salt).encode('utf-8')).hexdigest()
    return password_hash

def verify_password(stored_password, provided_password, salt):
    password_hash = hashlib.sha256((provided_password + salt).encode('utf-8')).hexdigest()
    return password_hash == stored_password

def perform_login(email, password):
    admin = User.query.filter_by(email=email, role='user').first()
    if hasattr(admin, "password"):
        password_verified = verify_password(admin.password, password, salt)
        if (password_verified == True):
            message = "login success"
            session['logged_in'] = True
            session['name'] = admin.first_name + " " + admin.last_name
            session['user_id'] = admin.id
        else:
            message = "login failed"
    else:
            message = "login failed"
   
    return message

user/routes.py
from flask import Blueprint, render_template, session, request, redirect, url_for
from user.views.user_view import (
    list_users_view,
    create_user_view,
    login_user_view,
    user_dashboard_view,
    user_aarp_tests_view,
    display_aarp_test_view,
    user_inogen_tests_view,
    user_jaya_tests_view,
    user_rif_tests_view,
    user_greeting_genie_tests_view,
    user_reports_view,
    user_charts_view
)
from user.tests.common_functions import TestCommonFunctions
from user.tests.common_functions import TestCreationFunctions

user_bp = Blueprint(
    "user_bp", __name__, template_folder="templates", static_folder="static"
)


@user_bp.route("/")
def home():
    return redirect(url_for("user_bp.login"))


def substring_after(s, delim):
    return s.partition(delim)[1]


@user_bp.route("/list")
def users():
    return list_users_view()


@user_bp.route("/create", methods=["GET", "POST"])
def create_user():
    return create_user_view()


@user_bp.route("/login", methods=["GET", "POST"])
def login():
    return login_user_view()


@user_bp.route("/logout")
def logout():
    session.pop("logged_in", None)
    return redirect(url_for("user_bp.login"))


@user_bp.route("/dashboard")
def dashboard():
    return user_dashboard_view()


@user_bp.route("/aarp-tests")
def aarp_tests():
    return user_aarp_tests_view()


@user_bp.route("/inogen-tests")
def inogen_tests():
    return user_inogen_tests_view()


@user_bp.route("/rif-tests")
def rif_tests():
    return user_rif_tests_view()


@user_bp.route("/jaya-tests")
def jaya_tests():
    return user_jaya_tests_view()


@user_bp.route("/greeting-genie-tests")
def greeting_genie_tests():
    return user_greeting_genie_tests_view()

@user_bp.route("/reports")
def reports():
    return user_reports_view()

@user_bp.route("/charts")
def charts():
    return user_charts_view()

@user_bp.route("/test-image-compare", methods=["POST"])
def upload_image():
    return TestCommonFunctions.run_image_compare(request)


@user_bp.route("/dashboard/aarp-dashboard", methods=["GET"])
def get_dashboard():
    return render_template("aarp.html")


@user_bp.route("/aarp-tests/<page_path>", methods=["GET", "POST"])
def display_run_aarp_tests(page_path):
    # print("Page Path: " + page_path)
    # print("Req Method: " + request.method)
    test_names = request.form.get('test_names')
    # print("Reqest test names: ")
    # print(test_names)
    
    if request.method.upper() == "GET":
        test_case_ids = request.args.get('test_case_ids')
        test_suite_id = request.args.get('test_suite_id')
        test_data = TestCommonFunctions.getSelectedTestdata(test_case_ids, test_suite_id)
        test_title = page_path.replace("-", " ").replace("aarp", "").strip().title()
        return display_aarp_test_view("aarp-test", page_path, test_title, test_data)
    
    elif request.method.upper() == "POST":
        if page_path.endswith("-file"):
            test_file = "test_" + page_path.replace("-file", "")
            test_file = test_file.replace("-", "_")
            return TestCommonFunctions.run_test_with_file(test_file, test_names)
        elif page_path.endswith("-url"):
            test_file = "test_" + page_path.replace("-url", "")
            test_file = test_file.replace("-", "_")
            return TestCommonFunctions.run_test_with_url(test_file, test_names)


@user_bp.route("/create-test-suite", methods=["POST"])

def create_test_suite():
    test_suite_name = request.form.get('test_suite_name')
    client_id = request.form.get('client_id')
    test_case_ids = request.form.get('test_case_ids')
    test_case_ids = request.form.get('test_case_ids')

    # Convert the string to a list (array) by splitting by comma
    test_case_ids_list = test_case_ids.split(',')

    # Convert the values to integers as the IDs are numeric
    test_case_ids_list = [int(id) for id in test_case_ids_list]
    
    return TestCreationFunctions.create_new_test_suite(test_suite_name, client_id, test_case_ids_list)

user/views/user_view.py
from flask import render_template, request, redirect, url_for, session
from user.controllers import user_controller, test_controller


def list_users_view():
    users = user_controller.get_all_users()
    return render_template("user/users.html", users=users)


def create_user_view():
    if request.method == "POST":
        first_name = request.form["first_name"]
        last_name = request.form["last_name"]
        email = request.form["email"]
        phone = request.form["phone"]
        password = request.form["password"]
        user_controller.create_user(first_name, last_name, email, phone, password)
        return redirect(url_for("user_bp.users"))
    return render_template("user/create_user_form.html")


def login_user_view():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        message = user_controller.perform_login(email, password)
        if message == "login success":
            return redirect(url_for("user_bp.dashboard"))
            # return render_template('user/dashboard.html')
        else:
            alert_message = "Incorrect username or password. Pease try again."
            return render_template("user/login_form.html", alert_message=alert_message)
    else:
        if session.get("logged_in") is not None:
            # return render_template('user/dashboard.html')
            return redirect(url_for("user_bp.dashboard"))
        else:
            return render_template("user/login_form.html")


def user_dashboard_view():
    if session.get("logged_in") is not None:
        all_tests = test_controller.get_all_tests()
        return render_template("user/dashboard.html", all_tests=all_tests)
    else:
        return redirect(url_for("user_bp.login"))


def user_aarp_tests_view():
    if session.get("logged_in") is not None:
        aarp_tests = test_controller.get_aarp_tests()
        test_cases = test_controller.get_all_test_cases()
        test_suits = test_controller.get_all_test_suites()
        return render_template("user/aarp.html", aarp_tests=aarp_tests, test_cases=test_cases, test_suits =test_suits)
    else:
        return redirect(url_for("user_bp.login"))


def user_inogen_tests_view():
    if session.get("logged_in") is not None:
        return render_template("user/inogen.html")
    else:
        return redirect(url_for("user_bp.login"))


def user_rif_tests_view():
    if session.get("logged_in") is not None:
        return render_template("user/rif.html")
    else:
        return redirect(url_for("user_bp.login"))


def user_jaya_tests_view():
    if session.get("logged_in") is not None:
        return render_template("user/jaya.html")
    else:
        return redirect(url_for("user_bp.login"))


def user_greeting_genie_tests_view():
    if session.get("logged_in") is not None:
        return render_template("user/greeting_genie.html")
    else:
        return redirect(url_for("user_bp.login"))

def user_reports_view():
    if session.get("logged_in") is not None:
        all_tests_dashboard = test_controller.get_tests_for_dashboard()
        return render_template("user/reports.html", all_tests_dashboard=all_tests_dashboard)
    else:
        return redirect(url_for("user_bp.login"))
    
def user_charts_view():
    if session.get("logged_in") is not None:
        return render_template("user/charts.html")
    else:
        return redirect(url_for("user_bp.login"))
        
def display_aarp_test_view(template, test_name, test_title, test_data):
    if session.get("logged_in") is not None:
        return render_template(
            "user/aarp/" + template + ".html",
            test_name=test_name,
            test_title=test_title,
            test_data = test_data,
        )
    else:
        return redirect(url_for("user_bp.login"))

user/templates/user/aarp.html
{% extends "user/base.html" %} {% block title %} AARP {% endblock %} {% block
content %}

<div class="defaultSec">
  <div class="aarpCheckList">
    <div class="header-checkList">
      <h2>AARP Dashboard</h2>
    </div>

    <div class="client-tabs aarp_tabs">
      <input
        type="radio"
        id="tabdashboard"
        name="client-tabs"
        checked="checked"
      />
      <label for="tabdashboard" class="tab-active">Overview</label>
      <div class="tab">
        <div class="tables">
          <table class="table">
            <thead>
              <tr>
                <th>Ticket Number</th>
                <th>Test Description</th>
                <th>Executed by</th>
                <th>Report link</th>
              </tr>
            </thead>
            <tbody class="">
              {% for test in aarp_tests %}
              <tr>
                <td>{{ test.test_ticket }}</td>
                <td>{{ test.test_description }}</td>
                <td>{{ test.first_name }} {{ test.last_name }}</td>
                <td>
                  <a href="static/pdf/{{test.test_report_file }}.pdf" download
                    ><img
                      src="{{ url_for('user_bp.static', filename='images/pdf-extesion.png') }}"
                  /></a>
                </td>
              </tr>

              <tr>
                {% endfor %}
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <input type="radio" id="tabTestSuite" name="client-tabs" />
      <label for="tabTestSuite" class="tab-active">Test Suite</label>
      <div class="tab">
        <p class="testSuiteSuccess" style="display: none;">New test suite is added successfully! </p>
        <div class="functionality_content testSuiteDiv">
          <div class="aarp_contents_first">
            {% for test_suit in test_suits %}
            <input type="hidden" id="test-suite-id" name = "test_suite_id" value= "{{ test_suit.id }}">
            <a
              href="aarp-tests/run-test?test_suite_id={{ test_suit.id }}"
              target="_blank"
              class="test-case-link test-case"
              >{{ test_suit.test_suite_name }}</a
            >
            {% endfor %}

            <!-- <a
              href="aarp-tests/aarp-master-checklist"
              target="_blank"
              class="test-case-link test-case"
              >Master Checklist</a
            > -->
            
          </div>

          <div class="aarp_contents_second_set">
            <a
              href="aarp-tests/aarp-image-comparison"
              target="_blank"
              class="test-case-link test-case"
              >UI comparision</a
            >
          </div>

        </div>
      </div>

      <input type="radio" id="tabsingletests" name="client-tabs" />
      <label for="tabsingletests" class="tab-active">Test Cases</label>
      <div class="tab">
        <div class="functionality_content">
          <div class="aarp_contents_first">
            
            {% for test_case in test_cases %}
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-{{ test_case.id }}"
                name="test-case-link"
                value="{{ test_case.test_case_name }}"
                class="test-case-link test-case"
                rel = "{{ test_case.id }}"
              />
              <label class="test-case-label" for="test-case-{{ test_case.id }}"
                >{{ test_case.test_case_name }}</label
              >
            </div>
            {% endfor %}

            <!-- <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link1"
                name="test-case-link"
                value="aarp-join-page-with-parameter"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link1"
                >Verify Join Page with parameters</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link2"
                name="test-case-link"
                value="aarp-renew-page-with-parameter"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link2"
                >Verify Renew Page with parameters</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link3"
                name="test-case-link"
                value="aarp-meta-tags"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link3"
                >Verify Meta Tags</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link4"
                name="test-case-link"
                value="aarp-https-link-verification"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link4"
                >Verify Https Links</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link5"
                name="test-case-link"
                value="aarp-meta-tags-index-follow"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link5"
                >Verify Page Meta Tags Index Follow</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link6"
                name="test-case-link"
                value="aarp-smetric-in-network"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link6"
                >Verify v60 and v197 in Smetric Network</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link7"
                name="test-case-link"
                value="aarp-verify-class-name"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link7"
                >Verify Class Names</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link8"
                name="test-case-link"
                value="aarp-cta-qs-button"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link8"
                >Verify CTA query string</label
              >
            </div> -->
          </div>
          <!-- <div class="aarp_contents_second_set">
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link9"
                name="test-case-link"
                value="aarp-verify-console-error"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link9"
                >Verify Console Error</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link10"
                name="test-case-link"
                value="aarp-verify-correct-premium-name"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link10"
                >Verify Correct Premium Name</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link11"
                name="test-case-link"
                value="aarp-cta-click"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link11"
                >Verify CTA Click Functionality</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link12"
                name="test-case-link"
                value="aarp-different-browser-widths"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link12"
                >Verify Page in Different Browser Widths</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link13"
                name="test-case-link"
                value="aarp-different-widths-with-scroll"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link13"
                >Verify Page by Scrolling</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link14"
                name="test-case-link"
                value="aarp-lg-copy-text-verification"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link14"
                >Verify Header phone number</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link15"
                name="test-case-link"
                value="aarp-category-level-accord"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link15"
                >Verify Category query string</label
              >
            </div>
            <div class="test-case-div">
              <input
                type="checkbox"
                id="test-case-link16"
                name="test-case-link"
                value="aarp-join-renew-with-parameter-py"
                class="test-case-link test-case"
              />
              <label class="test-case-label" for="test-case-link16"
                >Verify PYP Functionality</label
              >
            </div>
          </div> -->
        </div>
        <form  id="test-selection-Form" action="/user/aarp-tests/run-test" method="get">
          <input type="hidden" name="test_ids" id="test_ids" value="" />
          <button
            type="submit"
            id="submit-selected-tests"
            style="display: none"
          >
            Execute selected test cases
          </button>
        </form>
        <button onclick="handleSelectedTestcases()" class="btn-primary">Execute selected test cases</button>

        <div class = "test_suite_form" style="display: none">
          <div>
            <p class="step-text">Test Suite Name:</p>
            <input class="ticket-input" type="text" name="test_suite_name" id="test-suite-name" minlength="4" maxlength="20" required="" value="">
          </div>
          <input type="hidden" id="client-id" name="client_id" value="1">
          <input type="hidden" id="test-case-ids" name="test_case_ids" value="">
          <button onclick="handleNcreateTestSuite()" class="btn-primary">Create test suite</button>
        </div>
        <p class="report-error-msg" id="test_ids_empty_error"></p>
        <p class="report-error-msg" id="test_names_empty_error"></p>
        <img class="submit-loader" id="submit-loader" src="/user/static/images/Loader-spinning.gif" alt="Please wait..">
        <button onclick="showTestSuiteDiv()" class="btn-sec">Create new test suite</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="icon" type="image/x-icon" href="{{ url_for('user_bp.static', filename='images/favicon.ico') }}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('user_bp.static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('user_bp.static', filename='css/client_style.css') }}">
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,400;0,600;0,700;0,800;1,100;1,400;1,700;1,800&display=swap"
        rel="stylesheet">
</head>

<body>
    <div class="container">
        {% include "user/sidebar.html" %}
        <div class="main-content">
            {% include "user/header.html" %}
            <!-- {% block heading %} {% endblock %} -->
            {% block content %} {% endblock %}
        </div>
    </div>

    <script src="https://ddxp5xijf3rk2.cloudfront.net/js/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.27.2/axios.min.js"></script>
    <script type="text/javascript" src="{{ url_for('user_bp.static', filename='js/submit-handler.js') }}"></script>
</body>

</html>

user/templates/user/charts.html
{% extends "user/base.html" %}
{% block title %} greeting-genie {% endblock %}
{% block content %}
<div class="header-checkList">
    <h2>Charts Dashboard</h2>
</div>
<div class="client-tabs aarp_tabs">
    <div class="tab">
    </div>
</div>
{% endblock %}

user/templates/user/clients_tab_section.html
<div class="tabsection">
    <div class="tabs">
        <a href="{{ url_for('user_bp.aarp_tests') }}">
            <div class="tabcontent" id="Tab1">
                <img class="logo" src="{{ url_for('user_bp.static', filename='images/aarp.png') }}" alt="AARP logo">
                <p class="tabcontent-heading" >AARP</p>
            </div>
        </a>
        <a href="{{ url_for('user_bp.inogen_tests') }}">
        <div class="tabcontent" id="Tab2">
            <img class="logo" src="{{ url_for('user_bp.static', filename='images/inogen.png') }}" alt="Inogen logo">
            <p class="tabcontent-heading">Inogen</p>
        </div>
        </a>
        <a href="{{ url_for('user_bp.rif_tests') }}">
        <div class="tabcontent" id="Tab3">
            <img class="logo riflogo" src="{{ url_for('user_bp.static', filename='images/RIF.png') }}" alt="RIF logo">
            <p class="tabcontent-heading">RIF</p>

        </div>
        </a>
        <a href="{{ url_for('user_bp.jaya_tests') }}">
        <div class="tabcontent" id="Tab4">
            <img class="logo jayalogo" src="{{ url_for('user_bp.static', filename='images/jaya.png') }}"
                alt="jaya logo">
            <p class="tabcontent-heading">Jaya</p>
        </div>
        </a>
        <a href="{{ url_for('user_bp.greeting_genie_tests') }}">
        <div class="tabcontent" id="Tab5">
            <img class="logo gglogo" src="{{ url_for('user_bp.static', filename='images/GG.png') }}"
                alt="GreetingGenie logo">
            <p class="tabcontent-heading">Greeting Genie</p>
        </div>
        </a>
    </div>
</div>

user/templates/user/greeting_genie.html
{% extends "user/base.html" %}
{% block title %} greeting-genie {% endblock %}
{% block content %}
<div class="header-checkList">
    <h2>Greeting Genie Dashboard</h2>
</div>
<div class="client-tabs aarp_tabs">
    <div class="tab">
    </div>
</div>
{% endblock %}

user/templates/user/header.html
<div class="header">

    <div class="icon-section">
    
    <h1 class="heading">Dashboard</h1>

    <img class="aarp-icon" style="display: none;"
    src="{{ url_for('user_bp.static', filename='images/aarp.png') }}" alt="AARP">

    <img class="inogen-icon" style="display: none;"
    src="{{ url_for('user_bp.static', filename='images/inogen.png') }}" alt="INOGEN">

    <img class="rif-icon" style="display: none;"
    src="{{ url_for('user_bp.static', filename='images/RIF.png') }}" alt="RIF">

    <img class="jaya-icon" style="display: none;"
    src="{{ url_for('user_bp.static', filename='images/jaya.png') }}" alt="Jaya">

    <img class="gg-icon" style="display: none;"
    src="{{ url_for('user_bp.static', filename='images/GG.png') }}" alt="Greeting Genie">

    </div>

    <div class="profile-info">
        <img class="profile-picture" src="{{ url_for('user_bp.static', filename='images/user.png') }}"
            alt="Profile Picture">

        <div class="dropdown-menu">
            <a href="{{ url_for('user_bp.logout') }}" class="dropdown-item">Log Out</a>
        </div>
        <span>{% if session.name %} {{ session.name }} {% endif %}</span>
    </div>
</div>

user/templates/user/index.html
<!DOCTYPE html>
<html>

<head>
    <title>User Page title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('user_bp.static', filename='css/style.css') }}">
</head>

<body>
    <div class="wrapper">
        <div class="container">
            <h1>User Page</h1>
            <img src="{{ url_for('user_bp.static', filename='images/py-flask.webp') }}" alt="Py Flask" class="hero-img">
            <br /><br />
            <a href="#">User Page Link</a>
            <br />
            <a href="{{ url_for('admin_bp.home') }}">Link to Admin Page</a>
        </div>
    </div>

</body>

</html>

user/templates/user/jaya.html
{% extends "user/base.html" %}
{% block title %} jaya {% endblock %}

{% block content %}

<div class="header-checkList">
    <h2>Jaya Dashboard</h2>
</div>
<div class="client-tabs aarp_tabs">
    <div class="tab">
       
    </div>
</div>
    {% endblock %}

user/templates/user/rif.html
{% extends "user/base.html" %}
{% block title %} RIF {% endblock %}
{% block content %}
<div class="header-checkList">
    <h2>RIF Dashboard</h2>
</div>
<div class="client-tabs aarp_tabs">
    <div class="tab">
        
    </div>
</div>

    {% endblock %}

user/templates/user/sidebar.html
<div class="sidebar">
    <div class="sidebar-brand">
        <img class="tc-logo-image" src="{{ url_for('user_bp.static', filename='images/tc.png') }}" alt="TargetClose">
    </div>

    <ul class="sidebar-nav">
        <li class="sidebar-nav-itm">
            <a href="{{ url_for('user_bp.dashboard') }}" class="sidebar-nav-itm-dashboard">
                <img class="sidebar-nav-itm-icon" src="{{ url_for('user_bp.static', filename='images/dashboard.png') }}" alt="Dashboard Icon">
                <p>Dashboard</p>
            </a>
        </li>
        <hr>
        <li class="sidebar-nav-itm">
            <a href="{{ url_for('user_bp.aarp_tests') }}" class="sidebar-nav-itm-aarp">
                <img class="sidebar-nav-itm-icon" src="{{ url_for('user_bp.static', filename='images/aarp.png') }}" alt="aarp Icon">
                <p>AARP</p>
            </a>
        </li>
        <li class="sidebar-nav-itm">
            <a href="{{ url_for('user_bp.inogen_tests') }}" class="sidebar-nav-itm-inogen">
                <img class="sidebar-nav-itm-icon" src="{{ url_for('user_bp.static', filename='images/inogen.png') }}" alt="inogen Icon">
                <p>Inogen</p>
            </a>
        </li>
        <li class="sidebar-nav-itm">
            <a href="{{ url_for('user_bp.rif_tests') }}" class="sidebar-nav-itm-rif">
                <img class="sidebar-nav-itm-icon" src="{{ url_for('user_bp.static', filename='images/RIF.png') }}" alt="Pages Icon">
                <p>RIF</p>
            </a>
        </li>
        <li class="sidebar-nav-itm">
            <a href="{{ url_for('user_bp.jaya_tests') }}" class="sidebar-nav-itm-jaya">
                <img class="sidebar-nav-itm-icon" src="{{ url_for('user_bp.static', filename='images/jaya.png') }}" alt="Charts Icon">
                <p>Jaya</p>
            </a>
        </li>
        <li class="sidebar-nav-itm" >
         <a href="{{ url_for('user_bp.greeting_genie_tests') }}" class="sidebar-nav-itm-gg">
                <img class="sidebar-nav-itm-icon" src="{{ url_for('user_bp.static', filename='images/GG.png') }}" alt="gg Icon">
                <p>Greeting Genie</p>
            </a>
        </li>
        <hr>
        <li class="sidebar-nav-itm">
            <a href="{{ url_for('user_bp.charts') }}">
                <img class="sidebar-nav-itm-icon" src="{{ url_for('user_bp.static', filename='images/chart.png') }}" alt="Charts Icon">
                Charts
            </a>
        </li>
        <li class="sidebar-nav-itm">
            <a href="{{ url_for('user_bp.reports') }}">
                <img class="sidebar-nav-itm-icon" src="{{ url_for('user_bp.static', filename='images/report.png') }}" alt="Tables Icon">
                Reports
            </a>
        </li>
    </ul>
</div>